- hosts: Projeto-app
  become: yes
  tasks: 
    - name: Instalando Pip
      apt:
        name: python3-pip

    - name: Instalando Docker SDK Python
      pip:
        name: docker

    - name: Copiando o app para dentro da instancia
      copy:
        src: ./www
        dest: /www
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Web Server
      docker_container:
        name: app
        image: webdevops/php-apache:alpine-php7
        state: started
        ports:
          - "80:80"
        volumes:
          - /www:/app