- hosts: Projeto-app
  become: yes
  tasks: 
    - name: Instalando Pip
      apt:
        name: python3-pip

    - name: Instalando Docker SDK Python
      pip:
        name: docker

    - name: php-apache
      docker_container:
        name: app
        image: webdevops/php-apache:alpine-php7
        state: started
        ports:
          - "80:80"
        devices:
          - www:/app