- hosts: Projeto-app
  become: yes
  tasks: 
    - name: php-apache
      docker_container:
        name: app
        image: webdevops/php-apache:alpine-php7
        state: started
        ports:
          - "80:80"
        volumes:
          - ./www:/app
      